[package]
name = "chuck_norris"
version = "0.1.0"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.63"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
